### ISSUE TITLE
Navbar support?

### ISSUE THREAD

**Issue by samzhangjy** [vechai/vechaiui#19]
Hello! I love your library very much. However, I didn't find a component like a navbar for navigation... Is there a plan for adding it? Thanks a lot!!

**Comment by pepelele** [comment]
if you're talking about components, yes I have... Actually, I make them before vechaiui... about 60 components for the marketing page but honestly I'm considering whether to publish them  🥲

<img width="1680" alt="Screen Shot 2021-07-08 at 19 20 52" src="https://user-images.githubusercontent.com/84853682/124920598-ad3e0e80-e021-11eb-8bd3-ebd6ae0ffc9c.png">

**Comment by samzhangjy** [comment]
Oh... I think if the design fits for vechaiui, it would be fine! A proper navbar would make this library more complete.
