### ISSUE TITLE
[Question] VechaiUI didn't style the components?

### ISSUE THREAD

**Issue by samzhangjy** [vechai/vechaiui#22]
Hello. I followed the steps in the [documentation](https://www.vechaiui.com/) and tried to install VechaiUI. However, when I run the app, the components aren't styled:

![image.png](https://i.loli.net/2021/07/08/LsF1fui9YT6zPaB.png)

First, I created a blank project using `npx create-react-app`.

Then I installed the library using `yarn`:

```bash
yarn add @vechaiui/core @vechaiui/react @tailwindcss/forms
```

And I'm using the very same code as shown in the documentation:

```js
// ./src/App.js
import * as React from "react";
import { VechaiProvider, Button } from "@vechaiui/react";

function App() {
  return (
    <VechaiProvider>
      <Button>Hello Vechai</Button>
    </VechaiProvider>
  );
}

export default App;

```

And my `tailwind.config.js` is also copied from the docs:

```js
module.exports = {
  theme: {
    mode: "jit",
    purge: [
      //
      "./node_modules/@vechaiui/**/*.{js,ts,jsx,tsx}", // path to vechaiui
    ],
    darkMode: "class",
    // ...
  },
  // add VechaiUI plugin
  plugins: [
    require("@tailwindcss/forms"),
    require("@vechaiui/core"),
    // ...
  ],
};

```

The buttons have the `btn btn-md btn-outline` classes, and everything seem to work, except the style... (sorry for this terrible English...)

Sorry if I misunderstood something in the docs.... I'm actually a beginner in React. I just can't find a solution for this one...

**Comment by pepelele** [comment]
@samzhangjy oops sorry my I copied wrong config
`tailwind.config.js` should be:

```js
module.exports = {
  mode: "jit",
  purge: [
    "./node_modules/@vechaiui/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class", // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@vechaiui/core"),
  ],
}
```

I put all config in `theme`  😂

**Comment by pepelele** [comment]
You must include Tailwind in your CSS... more about tailwind document https://tailwindcss.com/docs/installation#include-tailwind-in-your-css

**Comment by samzhangjy** [comment]
Thank you...

Sam Zhang

________________________________
