### ISSUE TITLE
Components doesn't work

### ISSUE THREAD

**Issue by Mnigos** [vechai/vechaiui#54]
Hi I used the  `Button` component and It didn't apply style on it.

`_app.tsx`
```tsx
import React from 'react'
import type { AppProps } from 'next/app'
import { VechaiProvider, Button } from '@vechaiui/react'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <VechaiProvider>
      <Button>e</Button>
      <Component {...pageProps} />
    </VechaiProvider>
  )
}
```

`tailwind.config.ts`
```ts
export default {
  mode: 'jit',
  purge: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './node_modules/@vechaiui/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/forms'), require('@vechaiui/core')],
}

```
![image](https://user-images.githubusercontent.com/56691628/140421195-e0b4779e-bfac-433d-90da-d4a364d4f41e.png)

**Comment by pepelele** [comment]
You must import tailwind styles in _app.tsx
```jsx
import '../styles/globals.css';

```
globals.css

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

You can check basic setup here: https://stackblitz.com/edit/nextjs-pvx8qa?file=pages%2Findex.js

**Comment by Mnigos** [comment]
Yes I fixed that, and for now I see that tailwindcss styles applies, but venchaui doesn't

**Comment by pepelele** [comment]
You can download the demo or playground with stackblitz link ... I don't have enough context to find this bug

**Comment by Mnigos** [comment]
I see that config i recreated it, and it still doesn't work.

**Comment by Mnigos** [comment]
Ok, so to fix that error I was forced to create a new project.

**Comment by xingxinglieo** [comment]
i meet the same problem, did you solve it ?

> Ok, so to fix that error I was forced to create a new project.

**Comment by xingxinglieo** [comment]
> 

i forget add `VechaiProvider`, after adding it, some styles apply, but still any styles didn't work，like color. But i really need a ui library, so i copy all styles from the website `vechaiui.com` 😂

**Comment by mossen** [comment]
This is what you need to have in your `tailwind.config.js`:

```
module.exports = {
  mode: 'jit',
  purge: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './node_modules/@vechaiui/**/*.{js,ts,jsx,tsx}', // path to vechaiui
  ],
  plugins: [require('@tailwindcss/forms'), require('@vechaiui/core')],
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
}

```

**Comment by xingxinglieo** [comment]
> This is what you need to have in your `tailwind.config.js`:
> 
> ```
> module.exports = {
>   mode: 'jit',
>   purge: [
>     './pages/**/*.{js,ts,jsx,tsx}',
>     './components/**/*.{js,ts,jsx,tsx}',
>     './node_modules/@vechaiui/**/*.{js,ts,jsx,tsx}', // path to vechaiui
>   ],
>   plugins: [require('@tailwindcss/forms'), require('@vechaiui/core')],
>   darkMode: 'class', // or 'media' or 'class'
>   theme: {
>     extend: {},
>   },
>   variants: {
>     extend: {},
>   },
> }
> ```

Yes, the `tailwind.config.js` always has the config like this,but some styles don't work
![image](https://user-images.githubusercontent.com/48762792/153699120-2406d5a5-d922-47d1-b48d-32e792d8974e.png)
the icon is plain
