### ISSUE TITLE
[docs]: highlight code-block doesn't work

### ISSUE THREAD

**Issue by crashmax-dev** [vechai/vechaiui#59]
I think the problem is with the `onig.wasm`.
from [`shiki@0.9.13`](https://unpkg.com/browse/shiki@0.9.13/dist/) the file `onigasm.wasm` has been renamed to `onig.wasm`.

- Current deploy
![image](https://user-images.githubusercontent.com/15673111/144824498-23fa67fa-8c45-49fa-9611-329b5f8e3526.png)

 - Local development
![image](https://user-images.githubusercontent.com/15673111/144824356-410975c6-6e88-4004-a429-5fca3fc2d663.png)

Maybe the problem can be solved here:
https://github.com/vechai/vechaiui/blob/0ef9e1a5f11bc6dd1a2f92d7b86cd764eaba1720/docs/libs/react-shiki/index.js#L6

**Comment by tranbathanhtung** [comment]
tks for report ... fixed it
