### ISSUE TITLE
List of Icons

### ISSUE THREAD

**Issue by aviemet** [vechai/vechaiui#65]
Is there a list of the available icons in the `Icon` package? The docs for that component only show four status icons, but the source file exports eight, and the 'gift' icon which shows up throughout the docs is not one of them.

**Comment by pepelele** [comment]
`Icon` component makes icons accessible by adding a label ... we don't provide any icon set except 4 status icons & QuestionCircleIcon ... Any icon in the document only for demo purposes... You can use any icon set with vechai but I recommend `heroicons` or `radix-icons`
