### ISSUE TITLE
Vechai UI configuration give an errors with vite configuration + React v18

### ISSUE THREAD

**Issue by rahXephonz** [vechai/vechaiui#85]
Hello. 

I'm interesting to use vechaiui. But when i've added a vechai configuration in tailwind config
the errors appears when running the app. Does vechai UI support React v18?

How to solve this? 

![image](https://user-images.githubusercontent.com/77242429/185736249-33ea5c01-7d1f-434c-a66f-ecdd75335e84.png)

package.json
![image](https://user-images.githubusercontent.com/77242429/185736336-f07fa838-b7ba-4e78-92f9-c9f3d5c46c62.png)

my config tailwind
```js
module.exports = {
  content: [
    "./*.html",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./node_modules/@vechaiui/**/*.{js,ts,jsx,tsx}",
  ],
  plugins: [],
};
```

```ts
// app.tsx
import { BrowserRouter } from "react-router-dom";
import Navigation from "routes/Navigation";
import { QueryClient, QueryClientProvider } from "react-query";
import { VechaiProvider } from "@vechaiui/react";

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: false,
    },
  },
});

const App = () => {
  return (
    <BrowserRouter basename="/">
      <VechaiProvider>
        <QueryClientProvider client={queryClient}>
          <Navigation />
        </QueryClientProvider>
      </VechaiProvider>
    </BrowserRouter>
  );
};

export default App;
```

```ts
// main.tsx
import React from "react";
import { createRoot } from "react-dom/client";
// tailwind styles
import "styles/index.css";
import App from "./App";

type RootElement = Element | DocumentFragment;

const rootElement = document.getElementById("root");
const renderRoot = createRoot(rootElement as RootElement);

renderRoot.render(
  <React.Fragment>
    <App />
  </React.Fragment>,
);
```

**Comment by yuhang1995** [comment]
React 18 is not yet supported in the Vechai UI **https://github.com/vechai/vechaiui/issues/73#issuecomment-1108739309**

**Comment by rahXephonz** [comment]
> React 18 is not yet supported in the Vechai UI **[#73 (comment)](https://github.com/vechai/vechaiui/issues/73#issuecomment-1108739309)**

Hmm I see okay. Just downgrade my react application solved this issue now but I hope in the future there's have an update from vechai.
