### ISSUE TITLE
Charts, diagrams, graphs

### ISSUE THREAD

**Issue by roadiedev** [vechai/vechaiui#87]
Is it possible to add graph components to the library, or is there already some work being done on this?

Example of different types: https://demos.wrappixel.com/premium-admin-templates/react/flexy-react/stylish/#/charts/line-chart

**Comment by mhaidarhanif** [comment]
@paraparadox This might be relevant, can combine these two:

- https://tailwind-elements.com/docs/standard/components/charts
- https://react-chartjs-2.js.org

**Comment by roadiedev** [comment]
I really liked the charts from tailwind elements. Thank you very much @mhaidarhanif :+1: 
Closing this issue.

**Comment by mhaidarhanif** [comment]
You're welcome @paraparadox 👍
