### ISSUE TITLE
Can't bootstrap the project, yarn boot command fails

### ISSUE THREAD

**Issue by enochndika** [vechai/vechaiui#9]
i forked the repo to make improvements and fixe some bugs i've encountered but when i run `yarn boot`, the command line exit with code 417. as `yarn boot` is the combination of `yarn prestart` and `yarn build`, i've tried to run them separately but the same problem occurs with `yarn build`.

This error can be reproduced by downloading or cloning the repo and run `yarn  boot`

**Comment by pepelele** [comment]
@enochndika can you try it again... I think it's because of vechai core... I'll hide it for the time because I'm also having some issue  when compiling the plugin without jit mode

**Comment by enochndika** [comment]
Stil the same error, if you can check out `@vechaiui/toasted-notes` because it triggers the command line to exit.

**Comment by pepelele** [comment]
Can you show me a screenshot and let me know your environment... I cloned new repo but see nothing

**Comment by enochndika** [comment]
**OS** : Ubuntu 21.04 64bits
**Node** : 14.17.2
**yarn** : 1.22.5

![vechai](https://user-images.githubusercontent.com/51413750/124798601-71387a00-df4b-11eb-827c-ab2b06dd6292.png)

**Comment by pepelele** [comment]
@enochndika ah I see my bad... I use `concurrently` as a global package and I don't install it in this repo... Can you install it as global or I will fix it after my work

**Comment by enochndika** [comment]
I will install and try again
